python-setuptools-darcs: the build process seems to depend on 'darcsver'
 | source root is setuptools_darcs-1.2.9
 | patching sources
 | configuring
 | no configure script, doing nothing
 | building
 | running tests
 | Download error: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
 | Couldn't find index page for 'darcsver' (maybe misspelled?)
 | Download error: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
 | No local packages or download links found for darcsver>=1.2.0
 | Traceback (most recent call last):
 |   File "setup.py", line 79, in <module>
 |     zip_safe=False, # I prefer unzipped for easier access.
 |   File "/nix/store/r6xlmlf0amzwhkvkv0v656jgx7r299g7-python-2.6.5/lib/python2.6/distutils/core.py", line 113, in setup
 |     _setup_distribution = dist = klass(attrs)
 |   File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 260, in __init__
 |   File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 284, in fetch_build_eggs
 |   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 563, in resolve
 |   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 799, in best_match
 |   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 811, in obtain
 |   File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 327, in fetch_build_egg
 |   File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 434, in easy_install
 |   File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 475, in fetch_distribution
 | AttributeError: 'NoneType' object has no attribute 'clone'
 | builder for `/nix/store/rkm5fzs0p6hh45mvpzv0qqphmsjnyag8-python-setuptools-darcs-1.2.9.drv' failed with exit code 1
 | error: build of `/nix/store/rkm5fzs0p6hh45mvpzv0qqphmsjnyag8-python-setuptools-darcs-1.2.9.drv' failed

git-svn-id: https://svn.nixos.org/repos/nix/nixpkgs/trunk@22780 70bd8c7a-acb8-0310-9f0d-9cc1c95dcdbb